### ISSUE TITLE
Change batch processing to single event processing and add some measures for fail-safety and duplication avoidance

### ISSUE THREAD

**Issue by kaikae** [starfish-codes/ubersicht-ruby-sdk#5]
As agreed in the meeting we are going to change the batch processing approach to a single event approach:
Idea for an example method signature:
```
def ingest(transaction_type, event_code, time, payload)
  # do something
end
```
or
```
def ingest(transaction_type:, event_code:, time:, payload:)
  # do something
end
```
so the data can be passed in as a hash.
The SDK should in addition to that handle two things:
* queueing of events in case they can not be passed to ubersicht
* avoid duplication of events

**Comment by lazebny** [comment]
@kaikae could you check https://github.com/starfish-codes/ubersicht-ruby-sdk/pull/6 ?
